# Data Visualization Cheatsheet

## General Preprocessing

------------------------------------------------------------------------

### Gene Expression Analysis

```{r}


# Search for specific features (genes) present
Features(samples)

Features(samples)[Features(samples) %like% "CD56"]


```

### Batch Effect Analysis & Tweaking Metadata

```{r}

# Manually Update Sample Condition Names
print(unique(samples@meta.data$orig.sample))

samples@meta.data$orig.sample[samples@meta.data$orig.sample == "GSM6008408_PREP0128_ESint12162A_G9v1_SCb_BWH4_48h"] <- "48h"


# Check For Batch Effect
DimPlot(samples, reduction="integrated.cca", group.by="orig.sample")

DimPlot(samples, reduction="orig.umap", group.by="orig.sample")
DimPlot(samples, reduction="umap", group.by="orig.sample")

DimPlot(object=samples, reduction="umap", label = TRUE, pt.size = 0.5, group.by="orig.sample")


```

## Dimension Reduction Analysis

------------------------------------------------------------------------

### Reviewing Principal Component Analysis

```{r}

# --== Analyze Principal Components ==--
print(samples[["orig.pca"]], dims = 1:20, nfeatures = 30)

# Determine "dimensionality" by visualizing amount of change 
ElbowPlot(samples, reduction = "orig.pca")

VizDimLoadings(samples, dims = 1:2, reduction = "orig.pca")
```

### Plotting Dimension Reductionality

```{r}

# Generate Dimension Reduction Plot
figure <- DimPlot(object=samples, reduction="umap", label = TRUE, pt.size = 0.5)
ggsave("results/[DimPlot] Original UMAP.png", figure, width=6, height=4, dpi=300)


DimPlot(object=samples, reduction="orig.umap", label = TRUE, pt.size = 0.5)
DimPlot(object=samples, reduction="umap", label = TRUE, pt.size = 0.5)

VlnPlot(samples, features = CTM$Exhaust, log = TRUE, pt.size=0)


VlnPlot(samples, features = "LAG1", log = TRUE, pt.size=0)

# Generate Feature Plot

figure <- FeaturePlot(samples, cols=c("grey", "red"), reduction = "umap",
                      features = genesOfInterest)
ggsave("results/[FeaturePlot] Genes of Interest.png", figure, width=10, height=8, dpi=600)


```

## Investigating Clusters & Markers

------------------------------------------------------------------------

### Identify Cluster Markers

```{r}

# --== FindAllMarkers() ==--

de_markers <- FindAllMarkers(samples, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

# Print top n markers for each cluster
topMarkers <- de_markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)
View(topMarkers)

# View All Cluster (Idents) Names
levels(samples)

samples <- RenameIdents(samples, '3'="Neutrophils")


samples$cell.type <- samples@active.ident



# Remember that clusters /= PCs
# Markers are identified PER CLUSTERy


Idents(samples)

de_genes <- rownames(de_markers)
de_expr <- GetAssayData(samples1a, slot = "data")[de_genes, ]

```

### Generate Gene Set Modules

```{r}

object <- AddModuleScore(object = samples, features = CTM["Exhaust"] , name = "geneSet")


                                              
```

## Primary Heatmap Setup

------------------------------------------------------------------------

### Generate Average Expression Per Cluster

```{r}

# Set Up Annotation


# very useful and informative visualization :D
DimHeatmap(samples, dims = 1:2, cells = 500, balanced = TRUE)


expression_data <- GetAssayData(samples)[c("FOXP3", "LDHA", "FOXK1"), ]
cluster_assignments <- samples$cell.type

# Subset the expression data based on cluster assignments
cluster_expression <- expression_data[, cluster_assignments %in% c("1", "2")]

# Transpose the data so that rows represent genes and columns represent clusters
cluster_expression <- t(cluster_expression)

# Install and load the pheatmap package if not already installed
# install.packages("pheatmap")


cluster_expression_fixed <- apply(cluster_expression, 2, function(x) {
  replace(x, x == 0, NA)
})

gn <- c("FOXP3", "LDHA", "FOXK1", 'SOX9', 'HOXP', 'MKI67', 'EOMES', 'NEUROD2', 'SATB2', 'NR4A2', 'GAD1',"TFAM", "FOXK2", "TFEB", "LDHA", "PCSK9", "GPR84")
gn <- intersect(gn, rownames(GetAssayData(samples, slot = 'data')))
mat <- AverageExpression(samples, features = gn, layer = 'data',
                         group.by = c("cell.type", "orig.sample"))




```

### Set Up Heatmap

```{r}
# Create the heatmap using pheatmap
mat1 <- t(scale(t(as.matrix(mat$RNA))))

# set colors 
paletteLength <- 50
#myColor <- colorRampPalette(brewer.pal(11, "RdBu"))(paletteLength)
myColor1 <- colorRampPalette(rev(c( rgb(255,42,20,maxColorValue = 255), 
                                    "#FDAE61" ,"#FEE090", "#E0F3F8" ,"#74ADD1" ,"#4575B4")))(paletteLength)

myBreaks <- c(seq(min(mat1), 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(max(mat1)/paletteLength, max(mat1), length.out=floor(paletteLength/2)))


# set annotation
unique_combinations <- unique(paste0(samples$cell.type, "_", samples$orig.sample))

anno_col <- data.frame(
  Group_Condition = unique_combinations
)

split_group_time <- strsplit(anno_col$Group_Condition, "_")

anno_col <- data.frame(
  Type = sapply(split_group_time, `[`, 1),
  Time = sapply(split_group_time, `[`, 2)
)

rownames(anno_col) <- colnames(mat1)

time_order <- unique(anno_col$Time)

mat1 <- mat1[, order(match(anno_col$Time, time_order))]
anno_col <- anno_col[order(match(anno_col$Time, time_order)), ]

pheatmap::pheatmap(
  mat1,
  border_color = NA,
  color = myColor,
  breaks = myBreaks,
  annotation_col = anno_col,
  angle_col = 45
)
  

```

## Creating Subset Datasets

------------------------------------------------------------------------

### Investigating Exhausted Tc Populations

```{r}


# --== Subset By Cluster ==--
tSubset <- subset(samples, idents = c("T Cells", "CD4 T Cells", "CD8 T Cells"))

length(Cells(tSubset))


# --== Subset By Genes ==--

length(WhichCells(tSubset, expression = TIGIT > 1))



exhaustSubset <- subset(tSubset, cells = WhichCells(tSubset, expression = TIGIT > 1))
healthySubset <- subset(tSubset, cells = WhichCells(tSubset, expression = TIGIT < 1))

#validate
length(Cells(healthySubset))
length(WhichCells(healthySubset, expression = TIGIT > 1))


# violin plot of expression
tSubsetMerge <- merge(exhaustSubset, healthySubset)

tSubsetMerge$dataset <- c(
  rep("Exhausted", ncol(seurat_obj1@assays$RNA)), 
  rep("Healthy", ncol(seurat_obj2@assays$RNA)))


VlnPlot(exhaustSubset, features = genesOfInterest, log = TRUE, 
        pt.size = 0.1)
VlnPlot(healthySubset, features = genesOfInterest, log = TRUE, 
        pt.size = 0.1)


# Check subset size
print(nrow(cells_with_gene_expression))



exhaustSubset <- subset(seurat_obj, subset = RNA, gene_symbol = gene_of_interest)
```
